### ISSUE TITLE
<Hacktoberfest/>

### ISSUE THREAD

**Issue by simoneas02** [womenwhocoderecife/wwcode-hacktoberfest-2020#11]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7841344/93689926-8ff77e00-faa9-11ea-8e87-4d976b6cf59c.png">

[Link do figma](https://www.figma.com/file/8beCleoVlc3QcNvDLD0fls/Pull-request-day?node-id=0%3A1)

**Comment by keivalya** [comment]
Looking forward to it!! :D
