### ISSUE TITLE
Adiciona as props como desctruction do componente Session

### ISSUE THREAD

**Issue by simoneas02** [womenwhocoderecife/wwcode-hacktoberfest-2020#130]
No componente <Session/> temos três props: data, title e subtitle, a ideia desse card é que elas sejam passadas como destruction removendo essas três linhas de código da imagem abaixo.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/7841344/95017264-b29fa000-062e-11eb-94a8-dd69f4f3b9b4.png">

**Comment by cTahirih** [comment]
I can help this

**Comment by simoneas02** [comment]
Good job girl <3
